from django.contrib import admin

from georef.models import FROZEN_GUARDED_FIELDS, ReferenceFrame


@admin.register(ReferenceFrame)
class ReferenceFrameAdmin(admin.ModelAdmin):
    list_display = ("srid", "name", "origin_mark", "frozen", "valid_from")
    list_filter = ("frozen", "ellps")
    search_fields = ("name", "origin_mark")

    fieldsets = (
        (None, {"fields": ("srid", "name", "description")}),
        (
            "Origin",
            {
                "fields": ("origin_mark", "lat_0", "lon_0", "h_0", "ellps"),
                "description": "h_0 is ELLIPSOIDAL, never orthometric.",
            },
        ),
        ("False origin", {"fields": ("x_off", "y_off", "z_off")}),
        (
            "Provenance",
            {"fields": ("base_srid", "valid_from", "frozen", "notes")},
        ),
        (
            "Derived",
            {
                "fields": ("proj_pipeline",),
                "description": (
                    "Generated by the database from the parameters above. "
                    "Cannot be edited."
                ),
            },
        ),
    )

    def get_readonly_fields(self, request, obj=None) -> tuple[str, ...]:
        readonly = ["proj_pipeline"]
        if obj is not None:
            readonly.append("srid")
            if obj.frozen:
                readonly.extend(FROZEN_GUARDED_FIELDS)
                readonly.extend(["origin_mark", "base_srid"])
        return tuple(readonly)

    def has_delete_permission(self, request, obj=None) -> bool:
        """A frozen frame cannot be deleted — its coordinates would lose meaning."""
        return not (obj is not None and obj.frozen)
