"""The CRS definition registered in `spatial_ref_sys` for QGIS and GDAL.

`+proj=topocentric` cannot serve as a CRS — PROJ refuses to compose geographic
to topocentric ("Mismatched units between step 2 and 3") and drops the origin
from its WKT2. Orthographic about the same origin is the only definition those
tools can consume, so it is what gets registered, with the caveat carried in
the CRS's own REMARK so it travels with the layer.
"""

import pyproj

from georef.sql import SPATIAL_REF_SYS_UPSERT

#: Carried into the WKT so anyone inspecting the CRS in QGIS sees the limits.
#: `{pipeline}` is filled with the frame's generated pipeline.
CRS_REMARK = (
    "Horizontal DISPLAY definition for the topocentric ENU frame, for QGIS and "
    "GDAL only - it is NOT interchangeable with the frame. Reprojecting through "
    "it is off by h*d/N horizontally (~0.7 m over the glacier, because ortho "
    "ignores ellipsoidal height) and by d^2/2R in Z (~0.36 m, because ortho "
    "passes h through while the frame stores height above the tangent plane). Z "
    "is also shifted by the frame zoff and is NOT an altitude. Keep the project "
    "CRS on this SRID so nothing reprojects, and use georef_from_enu() for the "
    "exact 3D inverse. True 3D pipeline: {pipeline}"
)


def ortho_proj4(frame) -> str:
    """Orthographic proj4 string about the frame's origin.

    Built by hand rather than with `CRS.to_proj4()`, which warns about lossy
    conversion and rounds the origin to 13 significant figures. The frame's
    floats are written out in full.
    """
    return (
        f"+proj=ortho +lat_0={frame.lat_0} +lon_0={frame.lon_0} "
        f"+x_0={frame.x_off} +y_0={frame.y_off} "
        f"+ellps={frame.ellps} +units=m +no_defs"
    )


def crs_definition(frame) -> tuple[str, str]:
    """`(proj4text, srtext)` for the frame's `spatial_ref_sys` row.

    The WKT is generated by PROJ, then named and annotated through PROJJSON —
    `remarks` survives the round trip as a WKT `REMARK[...]` node.
    """
    proj4text = ortho_proj4(frame)

    definition = pyproj.CRS.from_proj4(proj4text).to_json_dict()
    definition["name"] = frame.name
    definition["remarks"] = CRS_REMARK.format(pipeline=frame.proj_pipeline)

    return proj4text, pyproj.CRS.from_json_dict(definition).to_wkt()


def register_frame_crs(cursor, frame) -> None:
    """Write the frame's CRS into `spatial_ref_sys`. Safe to re-run."""
    proj4text, srtext = crs_definition(frame)
    cursor.execute(SPATIAL_REF_SYS_UPSERT, [frame.srid, frame.srid, proj4text, srtext])
