# Generated by Django 6.0.6 on 2026-08-04 15:12

import datetime

import django.db.models.functions.comparison
from django.db import migrations, models

import georef.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReferenceFrame",
            fields=[
                (
                    "srid",
                    models.IntegerField(
                        help_text="SRID of the frame, in the private range 990000–991000. Also the SRID of the matching spatial_ref_sys row.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Short stable identifier, e.g. 'belvedere-enu'.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="What this frame is for and over which area it is valid.",
                        null=True,
                    ),
                ),
                (
                    "origin_mark",
                    models.CharField(
                        help_text="Label of the GNSS monument the origin sits on, e.g. 'D12'.",
                        max_length=45,
                    ),
                ),
                ("lat_0", models.FloatField(help_text="Origin latitude in degrees.")),
                ("lon_0", models.FloatField(help_text="Origin longitude in degrees.")),
                (
                    "h_0",
                    models.FloatField(
                        help_text="Origin height in metres — ELLIPSOIDAL, never orthometric."
                    ),
                ),
                (
                    "ellps",
                    models.CharField(
                        choices=[("GRS80", "GRS80"), ("WGS84", "WGS84")],
                        default="GRS80",
                        help_text="Reference ellipsoid name as understood by PROJ.",
                        max_length=16,
                    ),
                ),
                (
                    "x_off",
                    models.FloatField(
                        default=0.0,
                        help_text="Added to East so coordinates stay positive.",
                    ),
                ),
                (
                    "y_off",
                    models.FloatField(
                        default=0.0,
                        help_text="Added to North so coordinates stay positive.",
                    ),
                ),
                ("z_off", models.FloatField(default=0.0, help_text="Added to Up.")),
                (
                    "base_srid",
                    models.IntegerField(
                        default=32632,
                        help_text="CRS the origin coordinates were taken from.",
                    ),
                ),
                (
                    "datum_epoch",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Datum realisation epoch as a decimal year, e.g. 2008.00.",
                        max_digits=7,
                        null=True,
                    ),
                ),
                ("valid_from", models.DateField(default=datetime.date.today)),
                (
                    "frozen",
                    models.BooleanField(
                        default=False,
                        help_text="Once set, the origin and offsets can no longer change. Corrections require a new SRID.",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "proj_pipeline",
                    models.GeneratedField(
                        db_persist=True,
                        expression=georef.models.SqlConcat(
                            models.Value("+proj=pipeline"),
                            models.Value(" +step +proj=cart +ellps="),
                            models.F("ellps"),
                            models.Value(" +step +proj=topocentric +ellps="),
                            models.F("ellps"),
                            models.Value(" +lat_0="),
                            django.db.models.functions.comparison.Cast(
                                models.F("lat_0"), models.TextField()
                            ),
                            models.Value(" +lon_0="),
                            django.db.models.functions.comparison.Cast(
                                models.F("lon_0"), models.TextField()
                            ),
                            models.Value(" +h_0="),
                            django.db.models.functions.comparison.Cast(
                                models.F("h_0"), models.TextField()
                            ),
                            models.Value(" +step +proj=affine +xoff="),
                            django.db.models.functions.comparison.Cast(
                                models.F("x_off"), models.TextField()
                            ),
                            models.Value(" +yoff="),
                            django.db.models.functions.comparison.Cast(
                                models.F("y_off"), models.TextField()
                            ),
                            models.Value(" +zoff="),
                            django.db.models.functions.comparison.Cast(
                                models.F("z_off"), models.TextField()
                            ),
                        ),
                        help_text="PROJ pipeline generated from the parameters. Never hand-edited.",
                        output_field=models.TextField(),
                    ),
                ),
            ],
            options={
                "verbose_name": "reference frame",
                "db_table": "georef_reference_frame",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("srid__gte", 990000), ("srid__lte", 991000)
                        ),
                        name="reference_frame_srid_in_private_range",
                    )
                ],
            },
        ),
    ]
