# Generated by Django 6.0.6 on 2026-06-05 08:38

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("camera_name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("s3_bucket", models.CharField(max_length=255)),
                (
                    "s3_prefix",
                    models.CharField(
                        help_text="Folder/prefix in the bucket, e.g. camera-01/ or cam-a/",
                        max_length=512,
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("model", models.CharField(blank=True, max_length=100, null=True)),
                ("lens", models.CharField(blank=True, max_length=100, null=True)),
                ("focal_length_mm", models.FloatField(blank=True, null=True)),
                ("sensor_width_mm", models.FloatField(blank=True, null=True)),
                ("sensor_height_mm", models.FloatField(blank=True, null=True)),
                (
                    "pixel_size_um",
                    models.FloatField(
                        blank=True,
                        help_text="Physical pixel size in micrometers",
                        null=True,
                    ),
                ),
                (
                    "gsd",
                    models.FloatField(
                        blank=True,
                        help_text="Average ground Sampling Distance in cm/pixel",
                        null=True,
                    ),
                ),
                (
                    "easting",
                    models.FloatField(
                        blank=True,
                        help_text="Easting coordinate in meters (EPSG 32632)",
                        null=True,
                    ),
                ),
                (
                    "northing",
                    models.FloatField(
                        blank=True,
                        help_text="Northing coordinate in meters (EPSG 32632)",
                        null=True,
                    ),
                ),
                (
                    "elevation",
                    models.FloatField(
                        blank=True,
                        help_text="Elevation in meters (EPSG 32632)",
                        null=True,
                    ),
                ),
                (
                    "epsg_code",
                    models.IntegerField(
                        default=32632,
                        help_text="EPSG code for the coordinate reference system",
                    ),
                ),
                ("installation_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, dim=3, null=True, srid=32632
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["slug"], name="image_index_slug_d4914d_idx"),
                    models.Index(
                        fields=["s3_bucket", "s3_prefix"],
                        name="image_index_s3_buck_596ead_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CameraCalibration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calibration_date", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "model_id",
                    models.IntegerField(
                        choices=[
                            (0, "SIMPLE_PINHOLE"),
                            (1, "PINHOLE"),
                            (2, "SIMPLE_RADIAL"),
                            (3, "RADIAL"),
                            (4, "OPENCV"),
                            (5, "OPENCV_FISHEYE"),
                            (6, "FULL_OPENCV"),
                            (7, "FOV"),
                            (8, "SIMPLE_RADIAL_FISHEYE"),
                            (9, "RADIAL_FISHEYE"),
                            (10, "THIN_PRISM_FISHEYE"),
                            (11, "METASHAPE"),
                        ]
                    ),
                ),
                ("model_name", models.CharField(blank=True, max_length=50, null=True)),
                ("image_width_px", models.IntegerField()),
                ("image_height_px", models.IntegerField()),
                (
                    "intrinsic_params",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField()
                    ),
                ),
                (
                    "rotation_quaternion",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), blank=True, null=True, size=4
                    ),
                ),
                (
                    "translation_vector",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), blank=True, null=True, size=3
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calibrations",
                        to="image_index.camera",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("camera",),
                        name="unique_active_calibration_per_camera",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bucket", models.CharField(max_length=255)),
                ("object_key", models.CharField(max_length=1024, unique=True)),
                ("filename", models.CharField(max_length=255)),
                (
                    "s3_etag",
                    models.CharField(
                        blank=True, db_index=True, max_length=128, null=True
                    ),
                ),
                (
                    "s3_last_modified",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "file_size_bytes",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "datetime",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("width_px", models.IntegerField(blank=True, null=True)),
                ("height_px", models.IntegerField(blank=True, null=True)),
                ("mime_type", models.CharField(blank=True, max_length=100, null=True)),
                ("exif_data", models.JSONField(blank=True, null=True)),
                (
                    "rotation",
                    models.IntegerField(
                        default=0, help_text="Rotation in degrees (0, 90, 180, 270)"
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=500, null=True)),
                ("is_indexed", models.BooleanField(default=True)),
                ("indexed_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="image_index.camera",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["camera", "datetime"],
                        name="image_index_camera__0f32a0_idx",
                    ),
                    models.Index(
                        fields=["camera", "s3_last_modified"],
                        name="image_index_camera__368977_idx",
                    ),
                    models.Index(
                        fields=["bucket", "object_key"],
                        name="image_index_bucket_9b8b28_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("camera", "datetime"), name="unique_camera_datetime"
                    ),
                    models.UniqueConstraint(
                        fields=("bucket", "object_key"), name="unique_bucket_object_key"
                    ),
                ],
            },
        ),
    ]
