# Generated by Django 6.0.6 on 2026-06-05 09:02

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='camera_name',
            field=models.CharField(help_text='Human-readable camera name shown in admin and reports.', max_length=255),
        ),
        migrations.AlterField(
            model_name='camera',
            name='easting',
            field=models.FloatField(blank=True, help_text='Camera easting in the project CRS, usually EPSG:32632.', null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='elevation',
            field=models.FloatField(blank=True, help_text='Camera elevation in meters in the project CRS.', null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='epsg_code',
            field=models.IntegerField(default=32632, help_text='EPSG code of the coordinate reference system used for location fields.'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='focal_length_mm',
            field=models.FloatField(blank=True, help_text='Nominal focal length in millimeters.', null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='gsd',
            field=models.FloatField(blank=True, help_text='Average ground sampling distance in cm/pixel.', null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='installation_date',
            field=models.DateField(blank=True, help_text='Date when the camera was installed in the field.', null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='lens',
            field=models.CharField(blank=True, help_text='Lens model or description.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, dim=3, help_text='3D camera location as a PostGIS point geometry in the project CRS.', null=True, srid=32632),
        ),
        migrations.AlterField(
            model_name='camera',
            name='model',
            field=models.CharField(blank=True, help_text="Camera body model, e.g. 'Canon EOS 2000D'.", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='northing',
            field=models.FloatField(blank=True, help_text='Camera northing in the project CRS, usually EPSG:32632.', null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional free-text notes about installation, maintenance, or configuration.', null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='pixel_size_um',
            field=models.FloatField(blank=True, help_text='Physical pixel size in micrometers.', null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='s3_bucket',
            field=models.CharField(help_text='Name of the S3 bucket where this camera stores its images.', max_length=255),
        ),
        migrations.AlterField(
            model_name='camera',
            name='s3_prefix',
            field=models.CharField(help_text="Folder/prefix inside the bucket for this camera, e.g. 'camera-01/' or 'cam-a/'.", max_length=512),
        ),
        migrations.AlterField(
            model_name='camera',
            name='sensor_height_mm',
            field=models.FloatField(blank=True, help_text='Physical sensor height in millimeters.', null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='sensor_width_mm',
            field=models.FloatField(blank=True, help_text='Physical sensor width in millimeters.', null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Optional hardware serial number of the camera.', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='slug',
            field=models.SlugField(help_text="Short stable identifier for the camera, e.g. 'cam-01-north'. Useful in URLs, scripts, and filters.", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='cameracalibration',
            name='calibration_date',
            field=models.DateTimeField(help_text='Date and time when this calibration became valid or was computed.'),
        ),
        migrations.AlterField(
            model_name='cameracalibration',
            name='camera',
            field=models.ForeignKey(help_text='Camera to which this calibration belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='calibrations', to='image_index.camera'),
        ),
        migrations.AlterField(
            model_name='cameracalibration',
            name='image_height_px',
            field=models.IntegerField(help_text='Calibration image height in pixels.'),
        ),
        migrations.AlterField(
            model_name='cameracalibration',
            name='image_width_px',
            field=models.IntegerField(help_text='Calibration image width in pixels.'),
        ),
        migrations.AlterField(
            model_name='cameracalibration',
            name='intrinsic_params',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), help_text='Ordered list of intrinsic calibration parameters according to the selected model.'),
        ),
        migrations.AlterField(
            model_name='cameracalibration',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this is the currently active calibration for the camera.'),
        ),
        migrations.AlterField(
            model_name='cameracalibration',
            name='model_id',
            field=models.IntegerField(choices=[(0, 'SIMPLE_PINHOLE'), (1, 'PINHOLE'), (2, 'SIMPLE_RADIAL'), (3, 'RADIAL'), (4, 'OPENCV'), (5, 'OPENCV_FISHEYE'), (6, 'FULL_OPENCV'), (7, 'FOV'), (8, 'SIMPLE_RADIAL_FISHEYE'), (9, 'RADIAL_FISHEYE'), (10, 'THIN_PRISM_FISHEYE'), (11, 'METASHAPE')], help_text='Numeric identifier of the camera model used for calibration parameters.'),
        ),
        migrations.AlterField(
            model_name='cameracalibration',
            name='model_name',
            field=models.CharField(blank=True, help_text='Optional human-readable camera model name, e.g. OPENCV or METASHAPE.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cameracalibration',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional notes about the calibration procedure or source.', null=True),
        ),
        migrations.AlterField(
            model_name='cameracalibration',
            name='rotation_quaternion',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='Optional camera rotation as quaternion [qw, qx, qy, qz].', null=True, size=4),
        ),
        migrations.AlterField(
            model_name='cameracalibration',
            name='translation_vector',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='Optional camera translation vector [tx, ty, tz].', null=True, size=3),
        ),
        migrations.AlterField(
            model_name='image',
            name='bucket',
            field=models.CharField(help_text='S3 bucket containing the image object.', max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='camera',
            field=models.ForeignKey(help_text='Camera that acquired or owns this image.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='image_index.camera'),
        ),
        migrations.AlterField(
            model_name='image',
            name='datetime',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Acquisition timestamp of the image, from EXIF, filename, or external processing.', null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='exif_data',
            field=models.JSONField(blank=True, help_text='Parsed EXIF metadata stored as JSON.', null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='file_size_bytes',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Object size in bytes as reported by S3.', null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='filename',
            field=models.CharField(help_text='Basename of the image file, usually derived from the object key.', max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='height_px',
            field=models.IntegerField(blank=True, help_text='Image height in pixels.', null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='indexed_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this database row was first created during indexing.'),
        ),
        migrations.AlterField(
            model_name='image',
            name='is_indexed',
            field=models.BooleanField(default=True, help_text='Whether the image has been successfully indexed from S3.'),
        ),
        migrations.AlterField(
            model_name='image',
            name='label',
            field=models.CharField(blank=True, help_text='Optional tag or label for grouping or review.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='mime_type',
            field=models.CharField(blank=True, help_text='MIME type of the object, e.g. image/jpeg.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='object_key',
            field=models.CharField(help_text='Full S3 object key inside the bucket, including folders/prefixes.', max_length=1024),
        ),
        migrations.AlterField(
            model_name='image',
            name='rotation',
            field=models.IntegerField(default=0, help_text='Display rotation in degrees derived from EXIF orientation, usually 0, 90, 180, or 270.'),
        ),
        migrations.AlterField(
            model_name='image',
            name='s3_etag',
            field=models.CharField(blank=True, db_index=True, help_text='S3 ETag returned by the object listing; useful for change detection.', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='s3_last_modified',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp of the last modification reported by S3.', null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this database row was last updated.'),
        ),
        migrations.AlterField(
            model_name='image',
            name='width_px',
            field=models.IntegerField(blank=True, help_text='Image width in pixels.', null=True),
        ),
    ]
