# Generated by Django 6.0.6 on 2026-06-05 10:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("image_index", "0003_camera_is_active"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="image",
            name="unique_camera_datetime",
        ),
    ]
