# Generated by Django 6.0.6 on 2026-06-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("image_index", "0004_remove_image_unique_camera_datetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="preview_object_key",
            field=models.CharField(
                blank=True,
                help_text="S3 key of the pre-generated preview. Null if not yet generated.",
                max_length=1024,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="thumbnail_object_key",
            field=models.CharField(
                blank=True,
                help_text="S3 key of the pre-generated thumbnail (160×120 JPEG). Null if not yet generated.",
                max_length=1024,
                null=True,
            ),
        ),
    ]
