# Generated by Django 6.0.6 on 2026-06-05 21:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Photo",
            new_name="MeasurementPhoto",
        ),
        migrations.RenameField(
            model_name="measurement",
            old_name="point_photo",
            new_name="measurement_photo",
        ),
    ]
