# Generated by Django 6.0.6 on 2026-06-05 21:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0002_rename_photo_measurementphoto_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="measurementphoto",
            table="measurement_photos",
        ),
    ]
