# Generated by Django 6.0.6 on 2026-06-05 21:59

import django.db.models.deletion
from django.db import migrations, models

import surveys.models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0006_remove_measurement_measurement_photo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurementphoto",
            name="file_name",
            field=models.CharField(
                blank=True, editable=False, max_length=254, null=True
            ),
        ),
        migrations.AlterField(
            model_name="measurementphoto",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=surveys.models.measurement_photo_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="measurementphoto",
            name="measurement",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photo",
                to="surveys.measurement",
            ),
        ),
        migrations.AlterField(
            model_name="measurementphoto",
            name="path",
            field=models.CharField(
                blank=True, editable=False, max_length=254, null=True
            ),
        ),
    ]
