# Generated by Django 6.0.6 on 2026-06-11 13:53
#
# Extended by hand: replaces the legacy tables `2d_products`, `3d_products`
# and `volumes` (pandas/shapefile imports with truncated column names and no
# proper PKs) with clean Django-managed tables, copying their data over.
# The all-NULL legacy column `3d_products.average_no` is dropped.
# On a fresh database the legacy tables do not exist and the guarded SQL
# no-ops. The data copy is irreversible (restore from pg_dump backup).

import django.db.models.deletion
from django.db import migrations, models

# The legacy `volumes` table is identified by its pandas-style `index` column;
# it must be renamed before CreateModel claims the `volumes` table name.
RENAME_LEGACY_VOLUMES_SQL = """
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'volumes'
          AND column_name = 'index'
    ) THEN
        ALTER TABLE public.volumes RENAME TO volumes_legacy;
    END IF;
END $$;
"""

REVERSE_RENAME_LEGACY_VOLUMES_SQL = """
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_class c
        JOIN pg_namespace n ON c.relnamespace = n.oid
        WHERE n.nspname = 'public' AND c.relname = 'volumes_legacy'
    ) THEN
        ALTER TABLE public.volumes_legacy RENAME TO volumes;
    END IF;
END $$;
"""

COPY_LEGACY_DATA_SQL = """
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_class c
        JOIN pg_namespace n ON c.relnamespace = n.oid
        WHERE n.nspname = 'public' AND c.relname = '2d_products' AND c.relkind = 'r'
    ) THEN
        INSERT INTO products_2d (
            id, survey_id, data_type, file_format, reference_system, epsg,
            proj4, bounding_box, license, path, pixel_size, n_bands,
            file_size_bytes, is_uploaded, created_at, updated_at
        )
        SELECT
            id, fk_surveys, data_type, file_forma, reference_, epsg,
            proj4, bounding_b, license, path, pixel_size, n_bands,
            round(file_size_ * 1048576)::bigint, false, now(), now()
        FROM public."2d_products";
        PERFORM setval(
            pg_get_serial_sequence('products_2d', 'id'),
            (SELECT COALESCE(max(id), 1) FROM products_2d)
        );
        DROP TABLE public."2d_products";
    END IF;

    IF EXISTS (
        SELECT 1 FROM pg_class c
        JOIN pg_namespace n ON c.relnamespace = n.oid
        WHERE n.nspname = 'public' AND c.relname = '3d_products' AND c.relkind = 'r'
    ) THEN
        INSERT INTO products_3d (
            id, survey_id, data_type, file_format, reference_system, epsg,
            proj4, bounding_box, license, path, average_point_spacing,
            n_points, n_nodes, n_scalar_fields, texture,
            file_size_bytes, is_uploaded, created_at, updated_at
        )
        SELECT
            id, fk_surveys, data_type, file_forma, reference_, epsg,
            proj4, bounding_b, license, path, average_po,
            n_points, n_nodes, n_scalar_f, (texture <> 0),
            round(file_size_ * 1048576)::bigint, false, now(), now()
        FROM public."3d_products";
        PERFORM setval(
            pg_get_serial_sequence('products_3d', 'id'),
            (SELECT COALESCE(max(id), 1) FROM products_3d)
        );
        DROP TABLE public."3d_products";
    END IF;

    IF EXISTS (
        SELECT 1 FROM pg_class c
        JOIN pg_namespace n ON c.relnamespace = n.oid
        WHERE n.nspname = 'public' AND c.relname = 'volumes_legacy' AND c.relkind = 'r'
    ) THEN
        INSERT INTO volumes (survey_id, survey_prev_id, dv, density, density_uncertainty)
        SELECT survey_id, survey_prev_id, "dV", density, density_uncertainty
        FROM public.volumes_legacy
        ORDER BY index;
        DROP TABLE public.volumes_legacy;
    END IF;
END $$;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0009_move_core_tables_to_public"),
    ]

    operations = [
        migrations.RunSQL(
            sql=RENAME_LEGACY_VOLUMES_SQL,
            reverse_sql=REVERSE_RENAME_LEGACY_VOLUMES_SQL,
        ),
        migrations.CreateModel(
            name="Volume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dv",
                    models.FloatField(help_text="Volume difference in cubic metres."),
                ),
                (
                    "density",
                    models.FloatField(
                        blank=True, help_text="Density in kg/m³.", null=True
                    ),
                ),
                ("density_uncertainty", models.FloatField(blank=True, null=True)),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="volumes",
                        to="surveys.survey",
                    ),
                ),
                (
                    "survey_prev",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="volumes_as_previous",
                        to="surveys.survey",
                    ),
                ),
            ],
            options={
                "db_table": "volumes",
            },
        ),
        migrations.CreateModel(
            name="Product2D",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        help_text="Product type, e.g. ortofoto, dsm, pointcloud, mesh.",
                        max_length=64,
                    ),
                ),
                ("file_format", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "reference_system",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                ("epsg", models.IntegerField(blank=True, null=True)),
                ("proj4", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "bounding_box",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                ("license", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "path",
                    models.CharField(
                        blank=True,
                        help_text="Legacy local file path (pre-S3).",
                        max_length=512,
                        null=True,
                    ),
                ),
                (
                    "bucket",
                    models.CharField(
                        blank=True,
                        help_text="S3 bucket containing the product object. Null until uploaded.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "object_key",
                    models.CharField(
                        blank=True,
                        help_text="Full S3 object key inside the bucket. Null until uploaded.",
                        max_length=1024,
                        null=True,
                    ),
                ),
                ("s3_etag", models.CharField(blank=True, max_length=128, null=True)),
                ("s3_last_modified", models.DateTimeField(blank=True, null=True)),
                ("file_size_bytes", models.BigIntegerField(blank=True, null=True)),
                (
                    "is_uploaded",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the product file is present in S3 (set by index_s3_products).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pixel_size",
                    models.FloatField(
                        blank=True, help_text="Ground pixel size in metres.", null=True
                    ),
                ),
                ("n_bands", models.IntegerField(blank=True, null=True)),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_products",
                        to="surveys.survey",
                    ),
                ),
            ],
            options={
                "verbose_name": "2D product",
                "db_table": "products_2d",
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("bucket", "object_key"),
                        name="unique_product2d_bucket_object_key",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Product3D",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        help_text="Product type, e.g. ortofoto, dsm, pointcloud, mesh.",
                        max_length=64,
                    ),
                ),
                ("file_format", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "reference_system",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                ("epsg", models.IntegerField(blank=True, null=True)),
                ("proj4", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "bounding_box",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                ("license", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "path",
                    models.CharField(
                        blank=True,
                        help_text="Legacy local file path (pre-S3).",
                        max_length=512,
                        null=True,
                    ),
                ),
                (
                    "bucket",
                    models.CharField(
                        blank=True,
                        help_text="S3 bucket containing the product object. Null until uploaded.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "object_key",
                    models.CharField(
                        blank=True,
                        help_text="Full S3 object key inside the bucket. Null until uploaded.",
                        max_length=1024,
                        null=True,
                    ),
                ),
                ("s3_etag", models.CharField(blank=True, max_length=128, null=True)),
                ("s3_last_modified", models.DateTimeField(blank=True, null=True)),
                ("file_size_bytes", models.BigIntegerField(blank=True, null=True)),
                (
                    "is_uploaded",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the product file is present in S3 (set by index_s3_products).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "average_point_spacing",
                    models.FloatField(
                        blank=True,
                        help_text="Average point spacing in metres.",
                        null=True,
                    ),
                ),
                ("n_points", models.BigIntegerField(blank=True, null=True)),
                ("n_nodes", models.BigIntegerField(blank=True, null=True)),
                ("n_scalar_fields", models.IntegerField(blank=True, null=True)),
                (
                    "texture",
                    models.BooleanField(
                        blank=True,
                        help_text="Whether the mesh has a texture.",
                        null=True,
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_products",
                        to="surveys.survey",
                    ),
                ),
            ],
            options={
                "verbose_name": "3D product",
                "db_table": "products_3d",
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("bucket", "object_key"),
                        name="unique_product3d_bucket_object_key",
                    )
                ],
            },
        ),
        migrations.RunSQL(
            sql=COPY_LEGACY_DATA_SQL,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
