# Generated by Django 6.0.6 on 2026-06-11 14:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0011_adopt_views"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="measurementphoto",
            options={"verbose_name": "Measurement Monograph Photo"},
        ),
        migrations.AlterModelOptions(
            name="surveyhasinstrument",
            options={"verbose_name": "Survey-Instrument association"},
        ),
    ]
