# Generated by Django 6.0.6 on 2026-06-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0012_alter_measurementphoto_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivePoint",
            fields=[
                ("meas_id", models.IntegerField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=45)),
                ("last_measure_date", models.DateField(null=True)),
                ("east", models.FloatField()),
                ("north", models.FloatField()),
                ("h", models.FloatField()),
                ("is_fixed", models.BooleanField()),
            ],
            options={
                "verbose_name": "Active point (view)",
                "db_table": "active_points",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PointsMeasurement",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=45)),
                ("point_id", models.IntegerField()),
                ("is_fixed", models.BooleanField()),
                ("east", models.FloatField()),
                ("north", models.FloatField()),
                ("h", models.FloatField()),
                ("h_orto", models.FloatField(null=True)),
                ("lat", models.FloatField(null=True)),
                ("lon", models.FloatField(null=True)),
                ("survey_id", models.IntegerField()),
                ("survey_date", models.DateField(null=True)),
                ("survey_year", models.BigIntegerField(null=True)),
                ("meas_date", models.DateField(null=True)),
                ("meas_time", models.DateTimeField(null=True)),
                ("meas_strategy", models.CharField(max_length=25, null=True)),
                ("ds_east", models.FloatField(null=True)),
                ("ds_north", models.FloatField(null=True)),
                ("ds_h", models.FloatField(null=True)),
            ],
            options={
                "verbose_name": "Points measurement (view)",
                "db_table": "points_measurements",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PointsMovementFiltered",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=45)),
                ("survey_year", models.BigIntegerField(null=True)),
                ("is_fixed", models.BooleanField()),
                ("survey_date_fin", models.DateField(null=True)),
                ("survey_date_prev", models.DateField(null=True)),
                ("dt", models.IntegerField(help_text="Days between the two surveys.")),
                ("d_e", models.FloatField()),
                ("d_n", models.FloatField()),
                ("d_h", models.FloatField()),
                ("d", models.FloatField(help_text="3D displacement in metres.")),
                ("v", models.FloatField(help_text="Velocity in m/day.")),
                ("a", models.FloatField(help_text="Acceleration in m/day².")),
            ],
            options={
                "verbose_name": "Points movement filtered (view)",
                "verbose_name_plural": "Points movements filtered (view)",
                "db_table": "points_movement_filtered",
                "abstract": False,
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PointsMovementRaw",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=45)),
                ("survey_year", models.BigIntegerField(null=True)),
                ("is_fixed", models.BooleanField()),
                ("survey_date_fin", models.DateField(null=True)),
                ("survey_date_prev", models.DateField(null=True)),
                ("dt", models.IntegerField(help_text="Days between the two surveys.")),
                ("d_e", models.FloatField()),
                ("d_n", models.FloatField()),
                ("d_h", models.FloatField()),
                ("d", models.FloatField(help_text="3D displacement in metres.")),
                ("v", models.FloatField(help_text="Velocity in m/day.")),
                ("a", models.FloatField(help_text="Acceleration in m/day².")),
            ],
            options={
                "verbose_name": "Points movement raw (view)",
                "verbose_name_plural": "Points movements raw (view)",
                "db_table": "points_movement_raw",
                "abstract": False,
                "managed": False,
            },
        ),
    ]
