# Generated by Django 6.0.6 on 2026-06-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0018_measurement_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="point",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
