# Generated by Django 6.0.6 on 2026-08-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0020_measurement_geom_enu"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurement",
            name="h",
            field=models.FloatField(verbose_name="h (ellipsoidal)"),
        ),
    ]
