# Generated by Django 6.0.6 on 2026-08-05 10:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models

from surveys.sql import comment_columns, comment_table

MEASUREMENT_COLUMNS = (
    "geom", "east", "north", "h", "meas_date", "std_east", "std_north", "std_h",
    "meas_strategy", "meas_time", "notes", "lat", "lon", "h_orto", "geom_enu",
    "datum_realization", "height_type",
)  # fmt: skip

POINT_COLUMNS = ("label", "active", "is_fixed", "ref_date", "notes")
SURVEY_COLUMNS = ("date", "year", "notes")

TABLES = (
    ("measurements", MEASUREMENT_COLUMNS),
    ("points", POINT_COLUMNS),
    ("surveys", SURVEY_COLUMNS),
)

APPLY_COMMENTS = "".join(
    comment_table(table) + comment_columns(table, columns) for table, columns in TABLES
)
DROP_COMMENTS = "".join(
    comment_table(table, drop=True) + comment_columns(table, columns, drop=True)
    for table, columns in TABLES
)


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0025_null_2026_std"),
    ]

    operations = [
        # Comment-only change, so the database side is hand-written: Django's
        # AlterField re-emits `ALTER COLUMN ... TYPE` for every field, and
        # Postgres refuses that on east/north/h because the
        # `measurements_fill_geom_enu` trigger is declared UPDATE OF those
        # columns. Emitting just the comments also avoids 25 pointless
        # rewrites of a 568-row table.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterModelTableComment(
                    name="measurement",
                    table_comment="One GNSS measurement of a point during a survey campaign.",
                ),
                migrations.AlterModelTableComment(
                    name="point",
                    table_comment="Monitoring points: stakes on the glacier and fixed reference marks.",
                ),
                migrations.AlterModelTableComment(
                    name="survey",
                    table_comment="Survey campaigns.",
                ),
                migrations.AlterField(
                    model_name="measurement",
                    name="datum_realization",
                    field=models.CharField(
                        blank=True,
                        choices=[
                            ("RDN2008", "RDN2008 (ETRF2000, epoch 2008.0)"),
                            ("ETRF2000", "ETRF2000"),
                            ("ITRF2014", "ITRF2014"),
                        ],
                        db_comment="Reference frame realization the campaign was processed in.",
                        help_text="Reference frame realization the campaign was processed in.",
                        max_length=32,
                        null=True,
                    ),
                ),
                migrations.AlterField(
                    model_name="measurement",
                    name="east",
                    field=models.FloatField(
                        db_comment="Easting, m, EPSG:7791 (RDN2008 / UTM 32N)."
                    ),
                ),
                migrations.AlterField(
                    model_name="measurement",
                    name="geom",
                    field=django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        db_comment="Measurement position, EPSG:7791. Derived from east/north by trigger.",
                        null=True,
                        srid=7791,
                    ),
                ),
                migrations.AlterField(
                    model_name="measurement",
                    name="geom_enu",
                    field=django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        db_comment="Local ENU position, m (SRID 990001). Z is height above the tangent plane at D12 plus a 1000 m offset - NOT an altitude.",
                        dim=3,
                        editable=False,
                        help_text="Position in the local ENU frame, filled by a database trigger from east/north/h. Read-only: edit the source coordinates instead.",
                        null=True,
                        srid=990001,
                    ),
                ),
                migrations.AlterField(
                    model_name="measurement",
                    name="h",
                    field=models.FloatField(
                        db_comment="Ellipsoidal height, m (GRS80). Not a height above sea level.",
                        verbose_name="h (ellipsoidal)",
                    ),
                ),
                migrations.AlterField(
                    model_name="measurement",
                    name="h_orto",
                    field=models.FloatField(
                        blank=True,
                        db_comment="Orthometric height, m. Derived from h via the ITALGEO05 geoid.",
                        null=True,
                    ),
                ),
                migrations.AlterField(
                    model_name="measurement",
                    name="height_type",
                    field=models.CharField(
                        blank=True,
                        choices=[
                            ("ellipsoidal", "ellipsoidal"),
                            ("orthometric", "orthometric"),
                        ],
                        db_comment="Whether h is ellipsoidal or orthometric. Ellipsoidal everywhere.",
                        help_text="Should be 'ellipsoidal' everywhere; h_orto is computed internally from h using ITALGEO05 geoid model.",
                        max_length=16,
                        null=True,
                    ),
                ),
                migrations.AlterField(
                    model_name="measurement",
                    name="lat",
                    field=models.FloatField(
                        blank=True,
                        db_comment="Latitude, decimal degrees, WGS 84. Derived from east/north.",
                        null=True,
                    ),
                ),
                migrations.AlterField(
                    model_name="measurement",
                    name="lon",
                    field=models.FloatField(
                        blank=True,
                        db_comment="Longitude, decimal degrees, WGS 84. Derived from east/north.",
                        null=True,
                    ),
                ),
                migrations.AlterField(
                    model_name="measurement",
                    name="meas_date",
                    field=models.DateField(
                        blank=True, db_comment="Date the point was measured.", null=True
                    ),
                ),
                migrations.AlterField(
                    model_name="measurement",
                    name="meas_strategy",
                    field=models.CharField(
                        blank=True,
                        db_comment="GNSS method and receiver, e.g. 'RTK SPIN3'.",
                        max_length=25,
                        null=True,
                    ),
                ),
                migrations.AlterField(
                    model_name="measurement",
                    name="meas_time",
                    field=models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp of the measurement.",
                        null=True,
                    ),
                ),
                migrations.AlterField(
                    model_name="measurement",
                    name="north",
                    field=models.FloatField(
                        db_comment="Northing, m, EPSG:7791 (RDN2008 / UTM 32N)."
                    ),
                ),
                migrations.AlterField(
                    model_name="measurement",
                    name="notes",
                    field=models.CharField(
                        blank=True,
                        db_comment="Free-text notes.",
                        max_length=250,
                        null=True,
                    ),
                ),
                migrations.AlterField(
                    model_name="measurement",
                    name="std_east",
                    field=models.FloatField(
                        blank=True,
                        db_comment="Standard deviation of the easting, m.",
                        null=True,
                        verbose_name="std east",
                    ),
                ),
                migrations.AlterField(
                    model_name="measurement",
                    name="std_h",
                    field=models.FloatField(
                        blank=True,
                        db_comment="Standard deviation of the height, m.",
                        null=True,
                        verbose_name="std h",
                    ),
                ),
                migrations.AlterField(
                    model_name="measurement",
                    name="std_north",
                    field=models.FloatField(
                        blank=True,
                        db_comment="Standard deviation of the northing, m.",
                        null=True,
                        verbose_name="std north",
                    ),
                ),
                migrations.AlterField(
                    model_name="point",
                    name="active",
                    field=models.BooleanField(
                        blank=True,
                        db_comment="Whether the point is still part of the monitoring network.",
                        null=True,
                    ),
                ),
                migrations.AlterField(
                    model_name="point",
                    name="is_fixed",
                    field=models.BooleanField(
                        blank=True,
                        db_comment="True for stable reference marks; false for stakes on moving ice.",
                        null=True,
                    ),
                ),
                migrations.AlterField(
                    model_name="point",
                    name="label",
                    field=models.CharField(
                        blank=True,
                        db_comment="Point label, e.g. 'D12'.",
                        max_length=45,
                        null=True,
                    ),
                ),
                migrations.AlterField(
                    model_name="point",
                    name="notes",
                    field=models.CharField(
                        blank=True,
                        db_comment="Free-text notes.",
                        max_length=512,
                        null=True,
                    ),
                ),
                migrations.AlterField(
                    model_name="point",
                    name="ref_date",
                    field=models.DateField(
                        blank=True,
                        db_comment="Date the point was established.",
                        null=True,
                    ),
                ),
                migrations.AlterField(
                    model_name="survey",
                    name="date",
                    field=models.DateField(
                        blank=True, db_comment="Campaign date.", null=True
                    ),
                ),
                migrations.AlterField(
                    model_name="survey",
                    name="notes",
                    field=models.CharField(
                        blank=True,
                        db_comment="Free-text notes.",
                        max_length=254,
                        null=True,
                    ),
                ),
                migrations.AlterField(
                    model_name="survey",
                    name="year",
                    field=models.BigIntegerField(
                        blank=True, db_comment="Campaign year.", null=True
                    ),
                ),
            ],
            database_operations=[
                migrations.RunSQL(sql=APPLY_COMMENTS, reverse_sql=DROP_COMMENTS),
            ],
        ),
    ]
